### ISSUE TITLE
Params not running properly

### ISSUE THREAD

**Issue by jjohns3527** [lexelby/inkscape-embroidery#7]
When I run the Embroidery extension:
Embroider..  works
Params gives me the following error:

Traceback (most recent call last):
  File "embroider_params.py", line 618, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "embroider_params.py", line 592, in effect
    frame = SettingsFrame(tabs_factory=self.create_tabs)
  File "embroider_params.py", line 316, in __init__
    self.preset_chooser = wx.ComboBox(self, wx.ID_ANY, style=wx.CB_SORT)
wxAssertionError: C++ assertion "!(style & wxCB_SORT)" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py27/Phoenix/ext/wxWidgets/src/osx/combobox_osx.cpp(60) in Create(): wxCB_SORT not currently supported by wxOSX/Cocoa

**Comment by lexelby** [comment]
Fancy!  I see this is some kind of OSX-related issue.  It should be possible to work around this simply by sorting the values ourselves rather than using CB_SORT.

@jjohns3527 for now, could you try removing `, style=wx.CB_SORT` from line 316 in embroider_params.py?  You'll probably also need to remove `| wx.CB_SORT` from line 284.

If that allows Params to run, then I'll throw together a real fix.

**Comment by jjohns3527** [comment]
I modified embroider_params.py and now it will run without crashing inkscape  and gives the message below.  I do not get the tabbed box shown in your 12/6/17 **very nice** "how to" embroider the inkscape logo.  That was helpful to see what it should look like.  

I bet I need to adjust my install in some way 
2011 Mac Air OS 
"High Sierra 10.13.1;
Inkscape 0.92.2 5c3e80d, 2017-08-06;
X11 Xquartz 2.7.7   


Any thoughts on what to try or where to look?  Thanks very much for your help and for the program!


Error message:
Traceback (most recent call last):
  File "embroider_params.py", line 618, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "embroider_params.py", line 592, in effect
    frame = SettingsFrame(tabs_factory=self.create_tabs)
  File "embroider_params.py", line 316, in __init__
    self.preset_chooser = wx.ComboBox(self, wx.ID_ANY, style=wx.CB_SORT)
wxAssertionError: C++ assertion "!(style & wxCB_SORT)" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py27/Phoenix/ext/wxWidgets/src/osx/combobox_osx.cpp(60) in Create(): wxCB_SORT not currently supported by wxOSX/Cocoa

**Comment by lexelby** [comment]
I'm confused... It runs now but you still get the same error?  Or was that a mis-paste?

**Comment by jjohns3527** [comment]
It "runs" with the same error message which is confusing, because I modified "embroider_params.py".  But I think there must be another installation with a second copy of the file which I haven't edited.  I'll look into this more to see if I can modify the correct file and get back to you.  Thanks very much!

**Comment by oscarminus** [comment]
We had this issue, too. Removing the mentioned statements fixed this.

**Comment by lexelby** [comment]
@jjohns3527 Yup, there are two separate spots in the code where `CB_SORT` is used, so you'd have to fix both.

@oscarminus Thanks, that confirmation really helps!  I'll see if I can throw together a PR with a fix.

**Comment by jjohns3527** [comment]
I got a new computer and just installed your new embroidery extension and its fantastic!! I’ve been using the program from 2017 and it works well, but I see this new integrated program will be much better.

I can’t tell you how grateful to you I am for all the work on it.  

Can I make a piece of art for you?  I take photos, draw them, and then embroider the drawing, impress into clay to make porcelain mosaics.  I couldn’t do this work without your extension.  

www.jenniferjohnsonclay.com <http://www.jenniferjohnsonclay.com/>

If you have an image of a house or something meaningful, send it to me and I’ll make you a mosaic. Not to invade your privacy, but I have told people over the past year how great your program is, essential really to my art making, so I would love to reciprocate. 

Jennifer Johnson
jjohns3527@gmail.com <mailto:jjohns3527@gmail.com>

**Comment by lexelby** [comment]
Wow, that's so kind of you!! I've been really curious about your clay technique since you mentioned it, and I'd love to see what it looks like.

I'll send along a photo by email.  Thanks again!
